// Inlined by Vite at build time. A runtime fs read would resolve against the
// bundled server output, not the repo, and fail during prerender.
import videosMarkdown from '../../content/work/videos.md?raw';

/**
 * ONE shared hero-video pool for the whole domain (STYLEGUIDE.md §4.1, §7).
 *
 * Every page gets an edge-to-edge looping background video, picked
 * deterministically from this pool by route hash so a given page always keeps
 * "its" video across rebuilds. Pool size is irrelevant to the rule
 * (§9 Clarifications) — it is whatever `content/work/videos.md` currently holds.
 */

export type HeroVideo = { provider: 'vimeo' | 'youtube'; id: string };

function parsePool(): HeroVideo[] {
  const md = videosMarkdown;

  // Only the "## All videos" table. The "## Plain URL list" below it repeats the
  // same URLs and would double every entry's odds of being picked.
  const start = md.indexOf('## All videos');
  const end = md.indexOf('## Plain URL list');
  const table = md.slice(start === -1 ? 0 : start, end === -1 ? undefined : end);

  const seen = new Set<string>();
  const pool: HeroVideo[] = [];

  for (const line of table.split('\n')) {
    const vimeo = line.match(/vimeo\.com\/(\d+)/);
    const youtube = line.match(/(?:youtube\.com\/watch\?v=|youtu\.be\/)([\w-]{6,})/);

    const found: HeroVideo | null = vimeo
      ? { provider: 'vimeo', id: vimeo[1]! }
      : youtube
        ? { provider: 'youtube', id: youtube[1]! }
        : null;

    if (!found) continue;
    const key = `${found.provider}:${found.id}`;
    if (seen.has(key)) continue;
    seen.add(key);
    pool.push(found);
  }

  return pool;
}

export const HERO_VIDEOS: HeroVideo[] = parsePool();

/** Stable 32-bit hash. Same string always yields the same index. */
function hash(input: string): number {
  let h = 0;
  for (let i = 0; i < input.length; i++) {
    h = (h * 31 + input.charCodeAt(i)) >>> 0;
  }
  return h;
}

/** Deterministic pick: a route always resolves to the same video. */
export function videoForRoute(pathname: string): HeroVideo | null {
  if (HERO_VIDEOS.length === 0) return null;
  return HERO_VIDEOS[hash(pathname) % HERO_VIDEOS.length]!;
}

/** Background-embed URL: autoplay, muted, looping, no controls, no chrome. */
export function embedUrl(video: HeroVideo): string {
  if (video.provider === 'vimeo') {
    return `https://player.vimeo.com/video/${video.id}?autoplay=1&muted=1&loop=1&background=1&controls=0&dnt=1&playsinline=1`;
  }
  // YouTube needs `playlist` set to its own id for a single video to loop.
  return `https://www.youtube-nocookie.com/embed/${video.id}?autoplay=1&mute=1&loop=1&playlist=${video.id}&controls=0&modestbranding=1&playsinline=1&rel=0&disablekb=1`;
}

// ---------------------------------------------------------------- aspect ---

import videoMeta from '../../content/work/video-meta.json';

type Dimensions = { width: number; height: number; title?: string; poster?: string };
const META = videoMeta as Record<string, Dimensions>;

/** The frame every hero video is fitted into (STYLEGUIDE.md §4.1). */
export const FRAME_ASPECT = 1280 / 600;

/**
 * True aspect of the source, from `content/work/video-meta.json` (generated by
 * scripts/fetch-video-meta.mjs from each provider's oEmbed endpoint).
 *
 * Never hardcode a media aspect ratio: the frame is 2.13:1 and the sources are
 * not, so the embed has to be scaled to cover using the real number or it
 * pillarboxes inside its own iframe.
 */
export function aspectOf(video: HeroVideo): number {
  const dims = META[`${video.provider}:${video.id}`];
  if (!dims || !dims.height) return 16 / 9;
  return dims.width / dims.height;
}

// ------------------------------------------------------- the video library ---

/**
 * Full video library for /work/videos, parsed from the `## All videos` table in
 * `content/work/videos.md`. Titles, tags, and the filter-tab counts all come
 * from that table, so adding a row adds a tile and updates its tab count with
 * no code change.
 */
export type LibraryVideo = HeroVideo & {
  n: number;
  title: string;
  tags: string[];
  /** Filename in content/assets/video-posters, when one was fetched. */
  poster: string | null;
  width: number;
  height: number;
};

function parseLibrary(): LibraryVideo[] {
  const start = videosMarkdown.indexOf('## All videos');
  const end = videosMarkdown.indexOf('## Plain URL list');
  const table = videosMarkdown.slice(start === -1 ? 0 : start, end === -1 ? undefined : end);

  const out: LibraryVideo[] = [];

  for (const line of table.split('\n')) {
    // | # | Title | URL | Tags | Client | Year |
    const cells = line.split('|').map((c) => c.trim());
    if (cells.length < 6) continue;
    const [, num, title, url, tags] = cells;
    if (!num || !/^\d+$/.test(num)) continue;

    const vimeo = url?.match(/vimeo\.com\/(\d+)/);
    const youtube = url?.match(/(?:youtube\.com\/watch\?v=|youtu\.be\/)([\w-]{6,})/);
    const base: HeroVideo | null = vimeo
      ? { provider: 'vimeo', id: vimeo[1]! }
      : youtube
        ? { provider: 'youtube', id: youtube[1]! }
        : null;
    if (!base) continue;

    const dims = META[`${base.provider}:${base.id}`];
    out.push({
      ...base,
      n: Number(num),
      title: title ?? '',
      tags: (tags ?? '').split(/\s*,\s*/).filter(Boolean),
      poster: dims?.poster ?? null,
      width: dims?.width ?? 1280,
      height: dims?.height ?? 720,
    });
  }

  return out.sort((a, b) => a.n - b.n);
}

export const VIDEO_LIBRARY: LibraryVideo[] = parseLibrary();

/** Filter tabs, derived from the tags actually present. Counts are automatic. */
export function videoTags(): Array<{ label: string; count: number }> {
  const counts = new Map<string, number>();
  for (const video of VIDEO_LIBRARY) {
    for (const tag of video.tags) counts.set(tag, (counts.get(tag) ?? 0) + 1);
  }
  return [...counts.entries()]
    .map(([label, count]) => ({ label, count }))
    .sort((a, b) => b.count - a.count || a.label.localeCompare(b.label));
}

/** Watch embed: unlike the hero pool this one keeps controls and sound. */
export function watchUrl(video: HeroVideo): string {
  return video.provider === 'vimeo'
    ? `https://player.vimeo.com/video/${video.id}?autoplay=1&dnt=1&playsinline=1`
    : `https://www.youtube-nocookie.com/embed/${video.id}?autoplay=1&playsinline=1&rel=0`;
}
