/**
 * Generate `dist/_headers` and `dist/_redirects` for Cloudflare.
 *
 * Both are GENERATED, never hand-edited:
 *
 *  - `_redirects` is derived from the redirect table in SITEMAP.md, so the
 *    sitemap stays the single source of truth. Losing these 301s discards years
 *    of SEO equity on the old WordPress URLs.
 *
 *  - `_headers` carries a CSP whose script hashes are computed from the built
 *    HTML. Hand-maintaining hashes guarantees they drift the first time a
 *    component script changes; computing them means the CSP is always exact and
 *    never needs 'unsafe-inline'.
 *
 * Staging builds additionally get `X-Robots-Tag: noindex`. A crawlable staging
 * copy is duplicate content competing with the real site.
 *
 * Run: node scripts/postbuild.mjs   (wired into `npm run build`)
 */
import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('..', import.meta.url));
const dist = join(root, 'dist');

/* ------------------------------------------------------------ staging flag */

// Cloudflare sets one of these on a build. Anything that is not the production
// branch is treated as staging.
const branch =
  process.env.WORKERS_CI_BRANCH ?? process.env.CF_PAGES_BRANCH ?? process.env.BRANCH ?? '';
const isStaging = process.env.STAGING === '1' || (branch !== '' && branch !== 'main');

/* --------------------------------------------------------------- CSP hashes */

function walk(dir) {
  const out = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) out.push(...walk(full));
    else if (entry.endsWith('.html')) out.push(full);
  }
  return out;
}

const pages = walk(dist);

// CSP applies only to scripts the browser EXECUTES. `application/ld+json` and
// `application/json` are data blocks, so they are deliberately not hashed.
const DATA_TYPES = new Set(['application/ld+json', 'application/json']);
const hashes = new Set();

for (const page of pages) {
  const html = readFileSync(page, 'utf8');
  for (const match of html.matchAll(/<script([^>]*)>([\s\S]*?)<\/script>/g)) {
    const [, attrs, body] = match;
    if (/\ssrc=/.test(attrs) || body.trim() === '') continue;
    const type = attrs.match(/type="([^"]+)"/)?.[1] ?? 'text/javascript';
    if (DATA_TYPES.has(type)) continue;
    hashes.add(`'sha256-${createHash('sha256').update(body, 'utf8').digest('base64')}'`);
  }
}

/* ------------------------------------------------------- form endpoint origin */

// The contact form POSTs to a hosted endpoint whose URL lives in ONE place,
// FORM_ENDPOINT in src/pages/contact.astro, which renders it onto the form as
// `data-endpoint`. Read it back out of the built HTML so `connect-src` cannot
// drift from it. Without this, setting the endpoint would ship a form whose
// every submission is blocked by the CSP, and the failure is invisible until
// someone opens the console.
const formOrigins = new Set();
for (const page of pages) {
  const endpoint = readFileSync(page, 'utf8').match(/data-endpoint="(https:\/\/[^"]+)"/)?.[1];
  if (!endpoint) continue;
  try {
    formOrigins.add(new URL(endpoint).origin);
  } catch {
    throw new Error(`postbuild: FORM_ENDPOINT is not a valid URL: ${endpoint}`);
  }
}

const connectSrc = ["'self'", ...[...formOrigins].sort()].join(' ');
if (formOrigins.size > 0) {
  console.log(`postbuild: contact form endpoint allowed in connect-src (${[...formOrigins].join(', ')})`);
}

const csp = [
  "default-src 'self'",
  `script-src 'self' ${[...hashes].sort().join(' ')}`,
  // Inline style ATTRIBUTES are used for the rails and the video aspect vars.
  "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com",
  "font-src 'self' https://fonts.gstatic.com",
  "img-src 'self' data:",
  "frame-src https://player.vimeo.com https://www.youtube-nocookie.com",
  `connect-src ${connectSrc}`,
  "object-src 'none'",
  "base-uri 'self'",
  "form-action 'self'",
  "frame-ancestors 'none'",
  'upgrade-insecure-requests',
].join('; ');

const headers = `# GENERATED by scripts/postbuild.mjs — do not edit by hand.
# CSP script hashes are computed from the built HTML on every build.
${isStaging ? `# Staging build (branch: ${branch || 'unknown'}) — indexing disabled.\n` : ''}
/*
  Content-Security-Policy: ${csp}
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin
  X-Frame-Options: DENY
  Permissions-Policy: camera=(), microphone=(), geolocation=(), interest-cohort=()
${isStaging ? '  X-Robots-Tag: noindex, nofollow\n' : ''}
# Astro fingerprints these filenames, so they can be cached forever.
/_astro/*
  Cache-Control: public, max-age=31536000, immutable
`;

writeFileSync(join(dist, '_headers'), headers);

/* ----------------------------------------------------------------- redirects */

const sitemap = readFileSync(join(root, 'SITEMAP.md'), 'utf8');
const table = sitemap.slice(sitemap.indexOf('| From | To | Code |'));

const redirects = [];
for (const line of table.split('\n')) {
  const row = line.match(/^\|\s*`([^`]+)`\s*\|\s*`([^`]+)`\s*\|\s*(\d{3})\s*\|/);
  if (row) redirects.push({ from: row[1], to: row[2], code: row[3] });
}

if (redirects.length === 0) {
  throw new Error('postbuild: no redirects parsed from SITEMAP.md — refusing to ship an empty _redirects');
}

const width = Math.max(...redirects.map((r) => r.from.length));
const redirectFile = `# GENERATED by scripts/postbuild.mjs from the redirect table in SITEMAP.md.
# Do not edit by hand: edit SITEMAP.md and rebuild.
# ${redirects.length} redirects preserving the old WordPress URLs.

${redirects.map((r) => `${r.from.padEnd(width)}  ${r.to}  ${r.code}`).join('\n')}
`;

writeFileSync(join(dist, '_redirects'), redirectFile);

console.log(
  `postbuild: _headers (${hashes.size} CSP script hashes${isStaging ? ', staging noindex' : ''}) ` +
    `and _redirects (${redirects.length}) written to dist/`,
);
